# docker compose -f docker-compose.dev.yml down -v
# docker compose -f docker-compose.dev.yml up --build

services:
  postgres_db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-db
    platform: linux/x86_64
    restart: always
    environment:
      PG_PASSWORD: ${PG_PASSWORD}
      DEBUG: ${DEBUG}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_TEMPLATE: ${DB_TEMPLATE}
      DB_EXTENSION: ${DB_EXTENSION}
      REPLICATION_MODE: ${REPLICATION_MODE}
      REPLICATION_USER: ${REPLICATION_USER}
      REPLICATION_PASS: ${REPLICATION_PASS}
      REPLICATION_SSLMODE: ${REPLICATION_SSLMODE}
    ports:
      - '5432:5432'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8282:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pgdata:
    driver: local
